{% set name = "snntorch" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/snntorch-{{ version }}.tar.gz
  sha256: aab85d0be457488c7336a90af44d99dd38d1c3750bfb3b87269d2067316fdbd4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pytorch >=1.1.0
    - numpy
    - pandas
    - matplotlib-base
    - nir
    - nirtorch

test:
  imports:
    - snntorch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/jeshraghian/snntorch
  summary: Deep learning with spiking neural networks.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeshraghian
