{% set name = "snntorch" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snntorch-{{ version }}.tar.gz
  sha256: a2496aec3b542b94b5c0e959a7d812e25ba12019af2eeedc26ab1c6e9ee31246

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytorch >=1.1.0
    - numpy
    - pandas
    - matplotlib-base
    - nir
    - nirtorch

test:
  imports:
    - snntorch
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/jeshraghian/snntorch
  summary: Deep learning with spiking neural networks.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeshraghian
