{% set name = "snntorch" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snntorch-{{ version }}.tar.gz
  sha256: 080f4e00ebe2003b7ca2a5784cbc54cf8265c3ef42c3e54155d383869c8def8e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytorch >=1.1.0
    - numpy
    - pandas
    - matplotlib-base

test:
  imports:
    - snntorch
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/jeshraghian/snntorch
  summary: Deep learning with spiking neural networks.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeshraghian
